=== pamellaccar/gromacs_with_packmol/install/gromacs-2022.1/share/gromacs/top/residues.dtd
<!--                                                              -->
<!-- GROMACS Data type description (DTD). 

                This source code is part of
 
                 G   R   O   M   A   C   S
 
          GROningen MAchine for Chemical Simulations
 
                        VERSION 3.1
 
 Copyright (c) 1991-2002
 BIOSON Research Institute, Dept. of Biophysical Chemistry
 University of Groningen, The Netherlands
 
 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.
 
 If you want to redistribute modifications, please consider that
 scientific software is very special. Version control is crucial -
 bugs must be traceable. We will be happy to consider code for
 inclusion in the official distribution, but derived work must not
 be called official GROMACS. Details are found in the README & COPYING
 files - if they are missing, get the official version at www.gromacs.org.
 
 To help us fund GROMACS development, we humbly ask that you cite
 the papers on the package - you can find them in the top README file.
 
 Do check out http://www.gromacs.org , or mail us at gromacs@gromacs.org .
 
 And Hey:
 GROningen Mixture of Alchemy and Childrens' Stories

                                                            
 David van der Spoel 07/2001, 03/2002                        
 The authorative version of this document can be found at    
 http://www.gromacs.org/gromacs3.1.dtd                       
 and also in the library directory of your local GROMACS     
 installation.                                                
 
 Please use the following formal public identifier to identify it:
     "-//RESIDUES//DTD Residues XML V1.0//EN"

 <!DOCTYPE residues PUBLIC "-//RESIDUES//DTD Gromacs XML V3.1.0//EN"
                    "http://www.gromacs.org/residues.dtd"
                   [...]>
-->

<!-- This file defines the structure of the information necessary make
     a molecule from simple building blocks (called residues). The
     algorithm processing a sequence (or pdb file) should follow these
     steps:
     1. Do all the modification (moddef)
     2. Add all the links between residues
     3. Generate hydrogens
     4. Generate angle and torsion descriptions                     
-->

<!ELEMENT macromolecules (residues,macromolecule*)>

<!ELEMENT residues (residue*,linkdef*,moddef*)>

<!ELEMENT residue (ratom+,rbond*,rangle*,rimproper*,rdihedral*,raddh*)>
<!ATTLIST residue
          restype  ID    #REQUIRED
	  longname CDATA #REQUIRED>
<!-- We can not use ID here for atom names since there is no -->
<!-- hope to make them unique, e.g. all amino acids have the -->
<!-- same name for backbone atoms.                           -->
<!ELEMENT ratom EMPTY>
<!ATTLIST ratom
          name  CDATA #REQUIRED>
<!ELEMENT rbond EMPTY>
<!ATTLIST rbond
          a1 CDATA #REQUIRED
	  a2 CDATA #REQUIRED>	  
<!ELEMENT rangle EMPTY>
<!ATTLIST rangle
          a1 CDATA #REQUIRED
	  a2 CDATA #REQUIRED
	  a3 CDATA #REQUIRED>	  
<!ELEMENT rimproper EMPTY>
<!ATTLIST rimproper
          a1 CDATA #REQUIRED
	  a2 CDATA #REQUIRED
	  a3 CDATA #REQUIRED
	  a4 CDATA #REQUIRED>
<!ELEMENT rdihedral EMPTY>
<!ATTLIST rdihedral
          a1 CDATA #REQUIRED
	  a2 CDATA #REQUIRED
	  a3 CDATA #REQUIRED
	  a4 CDATA #REQUIRED>
<!-- Definition of how to add (hydrogen) atoms to molecules  -->
<!-- using a certain geometry (see GROMACS manual)           -->
<!ELEMENT raddh EMPTY>
<!ATTLIST raddh
          hclass   ( polar | aromatic | aliphatic ) 
	  addgeom  CDATA #REQUIRED
	  addnum   CDATA #REQUIRED
	  addto    CDATA #REQUIRED>
	  
<!-- Define a covalent link between two residues, given in restyp -->
<!-- and the atoms are given as well (atomprev and atomnext)      -->
<!-- A reference distance between the atoms does also have to be  -->
<!-- given in nm (but that does not have to be used).             -->
<!ELEMENT linkdef EMPTY>
<!ATTLIST linkdef
          linktype ID     #REQUIRED
	  restype  IDREFS #REQUIRED
	  atomprev CDATA  #REQUIRED
          atomnext CDATA  #REQUIRED
	  refdist  CDATA  #REQUIRED>

<!-- Description of termini, etc. or maybe other modifications too -->
<!-- It is important that the implementation deletes first, and    -->
<!-- adds atoms afterwards                                         --> 
<!ELEMENT moddef (moddelete*,modadd*,modrepl*)>
<!ATTLIST moddef
          modtype ID    #REQUIRED>
<!ELEMENT moddelete EMPTY>
<!ATTLIST moddelete
          delname CDATA #REQUIRED>
<!ELEMENT modreplace EMPTY>
<!ATTLIST modreplace
          oldname CDATA #REQUIRED
          newname CDATA #REQUIRED>
<!ELEMENT modadd EMPTY>
<!ATTLIST modadd
          addname CDATA #REQUIRED
          addbond CDATA #REQUIRED>

<!-- Generic stuff to define proteins etc. as built up from blocks -->
<!-- such as amino acids and HEME etc.                             -->
<!ELEMENT macromolecule (mblock+,mlink*,mmod*)>
<!ATTLIST macromolecule
          mname ID #REQUIRED>
<!ELEMENT mblock EMPTY>
<!ATTLIST mblock
          resname   ID    #REQUIRED
          restype   IDREF #REQUIRED
          protonated ( no | polar | all ) "polar">
<!ELEMENT mlink EMPTY>
<!ATTLIST mlink
          mlinktype  ( peptide | disulphide | special ) "peptide"
          resname   IDREFS #REQUIRED>
<!ELEMENT mmod EMPTY>
<!ATTLIST mmod
          resname IDREF #REQUIRED
          modtype IDREF #REQUIRED>
	  
<!-- Generic stuff to define proteins etc. as built up from blocks -->
<!-- such as amino acids and HEME etc.                             -->
<!ELEMENT macromolecule (mblock+,mlink*,mmod*)>
<!ATTLIST macromolecule
          mname ID #REQUIRED>
<!ELEMENT mblock EMPTY>
<!ATTLIST mblock
          resname   ID    #REQUIRED
          restype   IDREF #REQUIRED
          protonated ( no | polar | all ) "polar">
<!ELEMENT mlink EMPTY>
<!ATTLIST mlink
          mlinktype  ( peptide | disulphide | special ) "peptide"
          resname   IDREFS #REQUIRED>
<!ELEMENT mmod EMPTY>
<!ATTLIST mmod
          resname IDREF #REQUIRED
          modtype IDREF #REQUIRED>

=== pamellaccar/gromacs_with_packmol/install/gromacs-2022.1/share/top/residues.xml
<?xml version="1.0"?>
<!DOCTYPE residues SYSTEM "residues.dtd">

<residues>
  <residue restype="ACE">
    <ratom name="CA">
    <ratom name="HA1">
    <ratom name="HA2">
    <ratom name="HA3">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="CA" a2="HA1"/>
    <rbond a1="CA" a2="HA2"/>
    <rbond a1="CA" a2="HA3"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="C" a2="O"/>
    <raddh hclass="aliphatic" addgeom="4" addnum="3" addto="CA C O"/>
  </residue>

  <residue restype="ALA">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="HB3">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="HB3"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
    <rimproper a1="N" a2="-C" a3="CA" a4="H"/>
    <rimproper a1="-C" a2="-CA" a3="N" a4="-O"/>
    <rimproper a1="CA" a2="N" a3="C" a4="CB"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA"/>
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB"/>
    <raddh hclass="aliphatic" addgeom="4" addnum="3" addto="CB CA N"/>
  </residue>

  <residue restype="ARG">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="CG">
    <ratom name="HG1">
    <ratom name="HG2">
    <ratom name="CD">
    <ratom name="HD1">
    <ratom name="HD2">
    <ratom name="NE">
    <ratom name="HE">
    <ratom name="CZ">
    <ratom name="NH1">
    <ratom name="HH11">
    <ratom name="HH12">
    <ratom name="NH2">
    <ratom name="HH21">
    <ratom name="HH22">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="CG"/>
    <rbond a1="CG" a2="HG1"/>
    <rbond a1="CG" a2="HG2"/>
    <rbond a1="CG" a2="CD"/>
    <rbond a1="CD" a2="HD1"/>
    <rbond a1="CD" a2="HD2"/>
    <rbond a1="CD" a2="NE"/>
    <rbond a1="NE" a2="HE"/>
    <rbond a1="NE" a2="CZ"/>
    <rbond a1="CZ" a2="NH1"/>
    <rbond a1="CZ" a2="NH2"/>
    <rbond a1="NH1" a2="HH11"/>
    <rbond a1="NH1" a2="HH12"/>
    <rbond a1="NH2" a2="HH21"/>
    <rbond a1="NH2" a2="HH22"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
    <rimproper a1="N" a2="-C" a3="CA" a4="H"/>
    <rimproper a1="-C" a2="-CA" a3="N" a4="-O"/>
    <rimproper a1="CA" a2="N" a3="C" a4="CB"/>
    <rimproper a1="NE" a2="CD" a3="CZ" a4="HE"/>
    <rimproper a1="CZ" a2="NH1" a3="NH2" a4="NE"/>
    <rimproper a1="NH1" a2="HH11" a3="HH12" a4="CZ"/>
    <rimproper a1="NH2" a2="HH21" a3="HH22" a4="CZ"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA"/>
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CB CG CA"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CG CD CB"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CD NE CG"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="NE CD CZ"/>
    <raddh hclass="polar"     addgeom="3" addnum="2" addto="NH1 CZ NE"/>
    <raddh hclass="polar"     addgeom="3" addnum="2" addto="NH2 CZ NE"/>
  </residue>

  <residue restype="ASN">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="CG">
    <ratom name="OD1">
    <ratom name="ND2">
    <ratom name="HD21">
    <ratom name="HD22">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="CG"/>
    <rbond a1="CG" a2="OD1"/>
    <rbond a1="CG" a2="ND2"/>
    <rbond a1="ND2" a2="HD21"/>
    <rbond a1="ND2" a2="HD22"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
    <rimproper a1="N" a2="-C" a3="CA" a4="H"/>
    <rimproper a1="-C" a2="-CA" a3="N" a4="-O"/>
    <rimproper a1="CA" a2="N" a3="C" a4="CB"/>
    <rimproper a1="CG" a2="OD1" a3="ND2" a4="CB"/>
    <rimproper a1="ND2" a2="HD21" a3="HD22" a4="CG"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA"/>
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CB CG CA"/>
    <raddh hclass="polar"     addgeom="3" addnum="2" addto="ND2 CG CB"/>
  </residue>

  <residue restype="ASP">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="CG">
    <ratom name="OD1">
    <ratom name="OD2">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="CG"/>
    <rbond a1="CG" a2="OD1"/>
    <rbond a1="CG" a2="OD2"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
    <rimproper a1="N" a2="-C" a3="CA" a4="H"/>
    <rimproper a1="-C" a2="-CA" a3="N" a4="-O"/>
    <rimproper a1="CA" a2="N" a3="C" a4="CB"/>
    <rimproper a1="CG" a2="OD1" a3="OD2" a4="CB"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA"/>
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CB CG CA"/>
  </residue>

  <residue restype="ASPH">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="CG">
    <ratom name="OD1">
    <ratom name="OD2">
    <ratom name="HD2">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="CG"/>
    <rbond a1="CG" a2="OD1"/>
    <rbond a1="CG" a2="OD2"/>
    <rbond a1="OD2" a2="HD2"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
    <rimproper a1="N" a2="-C" a3="CA" a4="H"/>
    <rimproper a1="-C" a2="-CA" a3="N" a4="-O"/>
    <rimproper a1="CA" a2="N" a3="C" a4="CB"/>
    <rimproper a1="CG" a2="OD1" a3="OD2" a4="CB"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA"/>
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CB CG CA"/>
    <raddh hclass="polar"     addgeom="2" addnum="1" addto="OD1 CG CB"/>
  </residue>

  <residue restype="CYS2">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="SG">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="SG"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
    <rimproper a1="N" a2="-C" a3="CA" a4="H"/>
    <rimproper a1="-C" a2="-CA" a3="N" a4="-O"/>
    <rimproper a1="CA" a2="N" a3="C" a4="CB"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA"/>
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CB SG CA"/>
  </residue>

  <residue restype="CYSH">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="SG">
    <ratom name="HG">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="SG"/>
    <rbond a1="SG" a2="HG"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
    <rimproper a1="N" a2="-C" a3="CA" a4="H"/>
    <rimproper a1="-C" a2="-CA" a3="N" a4="-O"/>
    <rimproper a1="CA" a2="N" a3="C" a4="CB"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA"/>
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB"/>
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CB SG CA"/>
    <raddh hclass="aliphatic" addgeom="2" addnum="1" addto="SG CB CA"/>
  </residue>

  <residue restype="GLN">
    <ratom name="N">
    <ratom name="H">
    <ratom name="CA">
    <ratom name="HA">
    <ratom name="CB">
    <ratom name="HB1">
    <ratom name="HB2">
    <ratom name="CG">
    <ratom name="HG1">
    <ratom name="HG2">
    <ratom name="CD">
    <ratom name="OE1">
    <ratom name="NE2">
    <ratom name="HE21">
    <ratom name="HE22">
    <ratom name="C">
    <ratom name="O">
    <rbond a1="N" a2="H"/>
    <rbond a1="N" a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="CG"/>
    <rbond a1="CG" a2="HG1"/>
    <rbond a1="CG" a2="HG2"/>
    <rbond a1="CG" a2="CD"/>
    <rbond a1="CD" a2="OE1"/>
    <rbond a1="CD" a2="NE2"/>
    <rbond a1="NE2" a2="HE21"/>
    <rbond a1="NE2" a2="HE22"/>
    <rbond a1="C" a2="O"/>
    <rbond a1="-C" a2="N"/>
